import sys

with open('/home/user/faceless-short-studio/CHANGELOG.md', 'r') as f:
    content = f.read()

new_log = """
## v2.0.0 - 2026-08-31
* **MAJOR UPGRADE: The AI Director (LLM Engine):** Replaced the rigid template script generator with a true LLM agent (Groq API).
* **The "Paced Countdown" Script:** The AI Director now writes scripts specifically designed for sequential list reveals, pacing out each item over 5-10 seconds of B-roll instead of dumping it all at once.
* **The Engagement Trap:** The LLM is now trained to insert deliberate, minor spelling or logical errors into the middle of the script to drive viewers to correct it in the comments.
* **Creator Hub (SEO & Thumbnails):** `app.py` now features a Creator Hub that displays custom, highly-converting Thumbnail Prompts and SEO packages (Title, Tags, Description) generated by the AI Director to match the psychological angle of your video.
* **Zero Emojis & Memes:** Strict negative constraints added to the prompt bible to ensure the luxury, dark aesthetic is preserved without cartoonish interruptions or emoji compilation crashes.
"""

content = content.replace("# Studio Changelog / Ledger", "# Studio Changelog / Ledger\\n" + new_log)

with open('/home/user/faceless-short-studio/CHANGELOG.md', 'w') as f:
    f.write(content)
